export enum AllowedSection {
  GENERAL = 'GENERAL',
  TRACKS = 'TRACKS',
  DESCRIPTION = 'DESCRIPTION',
  TEAM_ACCESS = 'TEAM_ACCESS',
  INSIGHTS = 'INSIGHTS',
  PARTICIPANTS = 'PARTICIPANTS',
  WINNERS = 'WINNERS',
}
