export enum HackathonStatus {
  DRAFT = 'DRAFT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ENDED = 'ENDED',
  CANCELLED = 'CANCELLED',
  ARCHIVED = 'ARCHIVED',
}
